### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'mtime' when mounting

### ISSUE THREAD

**Issue by tstandley** [mxmlnkn/ratarmount#3] opened 2019-05-19 07:38 UTC
I get the following error whenever I try to mount
python ratarmount.py /taskonomy_data/taskonomy_small_ordered.tar /taskonomy_data_mnt

Creating offset dictionary for /taskonomy_data/taskonomy_small_ordered.tar ...
Traceback (most recent call last):
  File "ratarmount.py", line 447, in <module>
    recursive = args.recursive ),
  File "ratarmount.py", line 312, in __init__
    clearIndexCache = clearIndexCache, recursive = recursive )
  File "ratarmount.py", line 67, in __init__
    self.createIndex( file )
  File "ratarmount.py", line 242, in createIndex
    self.setFileInfo( path, {} )
  File "ratarmount.py", line 138, in setFileInfo
    mtime    = fileInfo.mtime      ,
AttributeError: 'dict' object has no attribute 'mtime'

**Comment by mxmlnkn** [comment] 2019-05-19 09:37
Ok, thanks for testing out the most bleeding edge commit so soon.

This should only happen if you had the problem in #2 in the prior version. In general, the problem is the missing strong types as the fileInfo argument can be either a dictionary or a named tuple and when writing the fix for #2, I forgot that both are allowed and assumed a tuple.

I'll try to write a test to reproduce this.

**Comment by mxmlnkn** [comment] 2019-05-19 10:29
Does this fix your issue?

**Comment by tstandley** [comment] 2019-05-20 00:18
Thanks for the update. I no longer get that particular issue, but after
about two hours, the system prints "Killed" and two new lines and then
returns to the prompt. Nothing is ever mounted.

**Comment by mxmlnkn** [comment] 2019-05-20 07:11
Which two lines do you get?

**Comment by mxmlnkn** [comment] 2019-05-20 07:19
Which two lines do you get?
I assume you get the timing outputs `Creating offset dictionary for ... took 2h`.

It's most likely that you simply run out of memory on your system and your out-of-memory killer kills the program. Can you monitor for that or use a system with more memory?

For example, I tried to open ImageNet on a system with 7GB RAM and it failed, so I allocated 64GB of RAM, which was finally enough.

Obnoxiously, the problem seems to be most often at the cpickling step. It almost looks like using cpickle more than doubles the memory footprint... I don't know why. It seems like it first writes the output to memory and only then writes it to file.

As a quick "fix" or just to test for my assumption, you could  empty out the `writeIndex` method, e.g., with a `return None` or by commenting out `pickle.dump`. Of course, this means that subsequent mounts will always take 2 hours for you as the index won't be cached. But at least I would know with more certainty that looking for a pickle alternative is the right choice of action.

**Comment by mxmlnkn** [comment] 2019-05-21 19:29
Closed as this seems to be another issue. Currently, I'd track your issue in #4 under the assumption, memory footprint is indeed the issue.

**Closed** 2019-05-21 19:28 UTC

**Comment by mxmlnkn** [comment] 2019-05-26 20:32
@tstandley I merged #5. If you want you can give it a try. The new default index should reduce the memory usage considerable. Remember to delete the old index or use the `-c` flag. If it still does not help, I'd be interested in the memory usage over time if you can access it or just the memory usage before it crashes. If it's something else entirely, I'm out of ideas.
