### ISSUE TITLE
Error: No such table: gzipindex

### ISSUE THREAD

**Issue by samyak-jain** [mxmlnkn/ratarmount#21] opened 2020-01-17 02:05 UTC
I have a ~500GB .tar.gz file. Trying to run ratarmount, I get the following after the creation of the index

```
Writing out TAR index to /mnt/data/final.tar.gz.index.sqlite took 0s and is sized 7143424 B
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ratarmount.py", line 1202, in __init__
    file.write( db.execute( 'SELECT data FROM gzipindex' ).fetchone()[0] )
sqlite3.OperationalError: no such table: gzipindex

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ratarmount", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.8/site-packages/ratarmount.py", line 1445, in cli
    fuseOperationsObject = TarMount(
  File "/usr/lib/python3.8/site-packages/ratarmount.py", line 1212, in __init__
    self.tarFile.export_index( filename = gzindex )
  File "indexed_gzip/indexed_gzip.pyx", line 721, in indexed_gzip.indexed_gzip._IndexedGzipFile.export_index
indexed_gzip.indexed_gzip.ZranError: ('export_index returned error: {}', -1)
```

**Comment by mxmlnkn** [comment] 2020-01-17 08:55
This seems rare. The underlying error is that my script assumes [`indexed_gzip`](https://github.com/pauldmccarthy/indexed_gzip) to be working. However, in this case it looks like `IndexedGzip.export_index` is unable to write to the temporary file created with `tempfile.mkstemp()`.

Some ideas:
  - Is your temporary directory writable?
  - Could it be that the disk where your temporary directory resides on is full?

**Comment by samyak-jain** [comment] 2020-01-17 15:53
How much space would I need in my tmpfs? My .tar.gz is ~500GB and the sqlite file is ~7MB. I have currently allocated 2GB for my tmpfs. Should that be enough? 
Also do I have to recreate the index to make this work now?

If I try mounting with the existing index it is just stuck and doesn't seem to be doing anything.

**Comment by samyak-jain** [comment] 2020-01-17 15:59
And from my understanding the error seems to have happened not because it couldn't write to the file but that the sql operation failed for some reason. 

Any idea what might have happened?

**Comment by mxmlnkn** [comment] 2020-01-17 16:15
> How much space would I need in my tmpfs? My .tar.gz is ~500GB and the sqlite file is ~7MB. I have currently allocated 2GB for my tmpfs. Should that be enough?
Yes, it should be enough, assuming all of the 2GB are available and not used up by other programs.

I can only speculate about the required size but from what I read in the issues, `indexed_gzip` creates a check point every 4MB of >extracted< data, so using the 500GiB as an estimate, this would be 128k checkpoints each of which are an estimate of 32B large, so 4MiB of total data. In the first place, the whole index is being created in memory first and can't be streamed to file. So, the created file should be smaller than the peak memory usage.

> And from my understanding the error seems to have happened not because it couldn't write to the file but that the sql operation failed for some reason.
> 
> Any idea what might have happened?

That's just typical Python'y way of doing things. I simply check if the gzip index data exists in the SQLite database and if not (exception thrown on access) , I try to export it from `indexed_gzip` and insert it into the database. This can take a while


> If I try mounting with the existing index it is just stuck and doesn't seem to be doing anything.

As already mentioned regarding your last question, when you are trying to call ratarmount with that incomplete index it is smart enough to notice the missing gzipindex data and will try to recreate it from scratch. When you activate verbose output `ratarmount --debug 2`, it should tell you such, although I see that this message should always show if tries this with an already existing index as it might be confusing.

After it has finished creating the gzip index, it should run into the same error you had above if it is reproducible.

---

/tmp being full or having wrong permissions was only a speculation. It might also be another bug. I could hack together something small which uses [memory-tempfile](https://pypi.org/project/memory-tempfile/) instead of the normal /tmp, that might already help. But you'd have to test it. But the real problem is `indexed_gzip.indexed_gzip.ZranError: ('export_index returned error: {}', -1)` and trying to debug that at the source would require adding helpful output and building `indexed_gzip` from source.

**Comment by mxmlnkn** [comment] 2020-01-17 17:32
I could test from Python first whether the temporary file is writable and give a file object to gzipped_indexed instead.
I could also try to create that temporary file in the same place as the SQLite database.
But as I can't reproduce the bug all of that would require testing on your side.

It would be helpful if you could test whether the error occurs with other .tar.gz files, especially smaller ones.

**Comment by samyak-jain** [comment] 2020-01-19 15:19
It looks like tmp was the issue. I modified the code to write to a file instead and it seems to have worked. 

Btw, Is there a way to mount it as rw? Since it seems to be read-only at the moment.

**Comment by mxmlnkn** [comment] 2020-01-19 16:21
> It looks like tmp was the issue. I modified the code to write to a file instead and it seems to have worked.

Thank you for trying this out yourself!

Do you know what in particular was the issue with your tmp?

I'll keep the issue open until I've added a simple fallback in case tmp is not available. The best option would be an update in the `gzipped_index` API but another option would be to simply fallback or even start with a file in the same directory as the SQLite file.

> Btw, Is there a way to mount it as rw? Since it seems to be read-only at the moment.

Currently, there is no such way. The "read-only" part is even in the heading of the Github page albeit luckily it didn't fit into the name "ratarmount" as rarotarmount would be troublesome to pronounce :smile:.

I guess, it would actually be possible for adding new files because those can be simply appended to the TAR. Even modifications would be possible because an appended new version of the file [should overwrite earlier versions](https://www.gnu.org/software/tar/manual/html_node/update.html#SEC63). However, I'm not sure whether ratarmount even correctly reads TAR files with multiple versions of the same file and this would not be space-efficient as the contents of the old versions won't be deleted. The latter would be especially problematic when interactively editing a file in a mounted TAR archive as every save or autosave would append a new version to the TAR.

A remedy for that could be to store the changes as an overlay in tmp (or elsewhere) and then force the user to commit the changes at once, e.g., when dismounting or with an extra command.

What wouldn't work in a performant way is deleting files. I could test around by simply setting the file names of files to be deleted to an empty string, but I'm not sure how normal TAR programs would handle that edge case. The correct way would be to delete the whole TAR block but that would require moving all the possibly 100GBs of data after it.

Another problem is compression. The above would work for uncompressed files and might even work relatively easily with bzip2 as you could simple delete the last end of stream block and then append new blocks even one block per modification or new file would work even if it would negatively influence compression efficiency. But, I'm not sure whether it would work with gzip compressed TAR files.

In general this sounds feasible and fun, I'd welcome pull requests or even try this myself.
However, my next goal is to parallelize the [bzip2 decoding backend](https://github.com/mxmlnkn/indexed_bzip2/issues/1) first. So, maybe after that I'll look into it.

**Comment by mxmlnkn** [comment] 2020-01-19 19:18
Btw, did you try archivemount? I think it has write support and should fairly well for smaller TAR archives. Ratarmount is only for the problems I encountered with very large archives.

**Comment by samyak-jain** [comment] 2020-01-22 13:15
I had allocated only 2GB for my tmpfs and the file ended being 4.5G. My guess is that's what ended up causing the issue. 

I am not sure how the fallback would work though. Is it possible for you to know in advance how much space you would need?

My particular use case is to delete. The reason being that I have a 500GB tarball but not enough space to extract it. I thought I could mount the tarball and move each folder one by one but I can't do that since it is read only.
I actually tried archivemount before going for ratarmount but it look like the time it would take for me to use archivemount would be insane. And I would need to transfer everything from the tarball all at once since subsequent mounts also take the same amount of time. 

How feasible is adding support for deletion? I'll try thinking of something else if it is difficult to do.

**Comment by mxmlnkn** [comment] 2020-01-22 17:23
> I had allocated only 2GB for my tmpfs and the file ended being 4.5G. My guess is that's what ended up causing the issue.

I didn't really expect the gzipindex to take that much space. However, as already compared [here](https://github.com/pauldmccarthy/indexed_gzip/issues/25#issuecomment-576251577), the check points in gzip require writing out 32kiB of internal decoded buffer, which is much more save data in contrast to two 64-bit integers per bzip2 block. I might experiment with reducing the number of gzip checkpoints or by forwarding this option to the CLI.

> I am not sure how the fallback would work though. Is it possible for you to know in advance how much space you would need?

Not really. I could calculate an estimation for the lower bound assuming a compression ratio of 1. But the fallback would be very simple: 1. check if it works 2. if any exception was thrown and caught, try with another location. However, I think I'll just go with using the location also used for the SQLite index because if it can't write there, then all hope is lost anyways as no SQLite index can be written out either.

> How feasible is adding support for deletion? I'll try thinking of something else if it is difficult to do.

As already mused, deletion would be one of the most difficult operations if you don't simply wanna mask it but really delete and shrink the TAR archive. In that case, on average it would require writing half the TAR archive size of bytes and that would have to be done for each change to be committed to the TAR. Disregarding the CPU time required for gzip compression and assuming a spinning disk with 100MB/s sequential write speed, it would take 85min to apply that change to your 500GB TAR ...  So, it does not combine well with a mounted and interactively modifiable TAR archive. 

Your best bet would be to simply use GNU tar with the `--delete` option but even that option won't work with compressed archives according to the manual ...

**Comment by samyak-jain** [comment] 2020-01-22 17:27
Would it be possible if I wanted to move everything? Meaning that since I know that everything has to be moved I will not have to delete stuff from the middle of the tar and instead I can keep deleting from the end. That way maybe it is possible to reduce the time by a lot. Does that make sense?

**Comment by mxmlnkn** [comment] 2020-01-22 18:07
I don't understand what you mean with moving. Do you simply want to rename a file inside the tar and with renaming I mean changing the full path of the file inside the tar. Changing the path inside the tar is relatively easy because the tar file format is simply a list of tar blocks with a header containing the file path among others and the raw data following the header.

Or do you want to move the raw TAR blocks inside the TAR around to get some arbitrary order?

```
.-------------------.-------------------.-------------------.-------------------.
| Header A : Data A | Header B : Data B | Header C : Data C | Header D : Data D |
'-------------------'-------------------'-------------------'-------------------'
```

In the above case, file D could relatively easily be deleted. Is that what you mean with "deleting from the end"? But, the ordering of the files inside the TAR is basically luck for most use cases.

**Comment by samyak-jain** [comment] 2020-01-22 18:12
By moving I meant moving the file out of the tarball. Copying from tarball to my filesystem (which already works) and then just deleting it from the tarball. 

If i have something like
Tar/
   A/
   B/
   C/

I would first copy C to my filesystem and then delete the C folder from the tar. So is deleting a folder from a tar possible? Since deleting a random folder would require a lot of tar blocks to be moved internally, if we could delete the folders in an order such that no blocks have to be internally moved then that should be fast. What do you think?

**Comment by mxmlnkn** [comment] 2020-01-22 19:44
So you basically want [in-place tar extraction](https://superuser.com/questions/156673/in-place-extract-tar-archive). If you wanna extract *everything*, then starting with the file at the end of the TAR and working back, this might indeed be doable. However, it would be hard to integrate into ratarmount. A standalone tool for that would be better. ratarmount could be a basis for that and it should actually be relative simple to hack together... at least now that seeking inside a TAR with ratarmount works, but I don't see any tool supporting in-place TAR extraction. Something like:

  1. Go over tar to generate the index for seeking just as ratarmount is doing
  2. for file in tar files starting from the one with the highest offset do
  2.1. Seek to file offset
  2.2. Write file contents to destination
  2.3. compressedTarFile.truncate( offsetInCompressed )

Of course, this first approach to in-place extraction would need a bit of additional working space possibly as large as the largest file in the TAR (if that largest file is coincidentally at the end and therefore the first to be extracted). But because it is compressed, you need additional space anyways.

Whether gzip decoding still works with this truncation correctly would have to be analyzed. For bzip2 compressed TARs it should very well work if you simply truncate the file to a bzip2 block boundary.

If your TAR to extract is on some server from which you downloaded it and if you have the bandwidth to spare to redownload it, then you could download it again and instead of saving it directly, you could extract the download stream as it comes in: `wget -O- https://github.com/mxmlnkn/ratarmount/raw/master/tests/single-file.tar.gz | tar xzf -`

**Comment by samyak-jain** [comment] 2020-01-28 08:27
Hmmm... So it looks like I'm on my own on this one. Do you know if it is possible to do just in place gzip decoding. I think that should make my work significantly easier.

**Comment by mxmlnkn** [comment] 2020-01-28 12:37
https://unix.stackexchange.com/questions/341458/decompress-gzip-file-in-place

```bash
total=$(stat --format='%s' urandom.img.gz) # bytes
total=$((1+$total/1024/1024)) # MiB
for ((offset=0; offset < $total; offset++))
do
    # read block
    dd bs=1M skip=$offset count=1 if=urandom.img.gz 2> /dev/null
    # delete (punch-hole) blocks we read
    fallocate --punch-hole --offset="$offset"MiB --length=1MiB urandom.img.gz
done | gunzip > urandom.img
```

You should test that solution with a gzip file you can live without...

**Comment by mxmlnkn** [comment] 2020-01-28 17:54
Note that this solution can actually be easily generalized into a `dcat` (destroying / destructing / deleting cat) and then even works for your original question for in-place extraction of a compressed tar. Definitely a macro I'll put in my .bashrc.

```bash
function dcat()
{
    local sizeB sizeMiB offsetMiB fileName

    fileName=$1
    if [[ ! -f $fileName ]]; then return 1; fi

    sizeB=$( stat --format='%s' -- "$fileName" ) # bytes
    sizeMiB=$(( ( $sizeB + 1024*1024 - 1 ) / ( 1024*1024 ) )) # ceil( Bytes / MiB )

    for (( offsetMiB = 0; offsetMiB < $sizeMiB; ++offsetMiB )); do
        dd bs=1M skip=$offsetMiB count=1 if="$fileName" 2> /dev/null
        fallocate --punch-hole --offset="$offsetMiB"MiB --length=1MiB -- "$fileName"
    done
}

dcat firefox-66.0.5.tar.bz2 | tar -xjf-
```

Worked for me. You can use Ctrl+Z to pause decompressing and check that the file indeed gets partially deleted from the file system:

```
stat /opt/firefox-66.0.5.tar.bz2
  File: firefox-66.0.5.tar.bz2
  Size: 62099150  	Blocks: 121288     IO Block: 4096   regular file
dcat firefox-66.0.5.tar.bz2 | tar -xjf-
^Z
[1]+  Stopped                 dcat firefox-66.0.5.tar.bz2 | tar -xjf-
stat /opt/firefox-66.0.5.tar.bz2
  File: firefox-66.0.5.tar.bz2
  Size: 62099150  	Blocks: 106952     IO Block: 4096   regular file
```
And beautifully, stat now only shows 107k blocks being used instead of 121k before the operation.

**Closed** 2020-04-10 17:04 UTC
Labels: bug
