### ISSUE TITLE
Cannot create a directory in an uncompressed tar and commit

### ISSUE THREAD

**Issue by fanfan70** [mxmlnkn/ratarmount#125] opened 2023-12-18 15:34 UTC
Hello,
I'm trying to use write overlay on an uncompressed tar.
I managed to create a file in a mounted tar and commit the modification, but that doesn't work with a new dir (or I am misunderstanding something).
By the way, the call to the ratarmount command issues this error message:
>shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

Here is an example to reproduce the problem.
Regards!

```
#!/bin/bash

set -xv
set -o errexit
set -o nounset

OVERLAY_DIR=/tmp/overlay
MOUNT_POINT=/tmp/mnt

function umount_tar()
{
  if [[ -n $(mount|grep "FuseMount on $MOUNT_POINT type") ]]; then
    fusermount -u $MOUNT_POINT
  fi
}

function create_dummy_tar()
{
  local tar_dir=/tmp/example_tar
  tar=/tmp/example.tar
  rm -rf $tar* $tar_dir
  mkdir -p $tar_dir/dir1
  ls -al / > $tar_dir/file1
  cd $tar_dir
  tar cf $tar .
  rm -r $tar_dir
}

create_dummy_tar

rm -rf $OVERLAY_DIR $MOUNT_POINT
mkdir -p $OVERLAY_DIR $MOUNT_POINT

# mount tar
ratarmount --write-overlay $OVERLAY_DIR $tar $MOUNT_POINT
# shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

# add empty directory
mkdir -p $MOUNT_POINT/dir2

# umount tar
umount_tar

# commit changes
ratarmount --commit-overlay --write-overlay $OVERLAY_DIR $tar $MOUNT_POINT <<EOT
commit
EOT
# shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

**Comment by fanfan70** [comment] 2023-12-18 15:41
This works if you replace `mkdir -p $MOUNT_POINT/dir2` with something like `ls -al / > $MOUNT_POINT/file2`.

**Comment by mxmlnkn** [comment] 2024-02-23 09:37
I'm sorry for the late answer. I seem to have missed this issue.

`shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory`

This happens because you do `cd $tar_dir`, then `rm -rf $OVERLAY_DIR $MOUNT_POINT`, and then call ratarmount. It happens because the current working directory does not exist anymore as you have deleted it. I think You meant to change the directory back to the previous one after creating the tar. You can do this with `cd -` at the end of `create_dummy_tar` or by replacing the `{}` with `()` around `create_dummy_tar`. However, the latter option would also result in `tar_dir`, which is set inside the function, not being usable outside of the function.

I also needed to add a  `sleep 1` before the `unmount_tar` because FUSE is sometimes slow and takes a while to set up and before it can be unmounted again. Else, I got `fusermount: failed to unmount /tmp/mounted: Device or resource busy`.

Now, I can reproduce the original issue. `dir2` should have been committed but it is not. Thank you for adding the detailed reproducer script!

**Closed** 2024-02-23 09:37 UTC
