### ISSUE TITLE
Can you force the Metadata Index Cache to write to ~/.ratarmount?

### ISSUE THREAD

**Issue by mceachen** [mxmlnkn/ratarmount#45] opened 2020-12-09 04:58 UTC
First off: HOLY CRAP `ratarmount` IS AWESOME. :tada: :+1: :100: Thank you!

If you point `ratarmount` at a tarball on a remote filesystem, SQLite will fail to write the index sidecar.

Is there a way to force ratarmount to write to `~/.ratarmount` instead?

**Comment by mxmlnkn** [comment] 2020-12-09 08:58
Thank you for your feedback :).

 Normally, ratarmount should detect whether the TAR file destination is writable and fall back to writing to `~/.ratarmount` automatically. If this doesn't work, it seems to be a bug. 

As a workaround, until I look deeper into that and fix it, the version on master has a [`--index-file`](https://github.com/mxmlnkn/ratarmount/blob/master/ratarmount.py#L1662) option, where you can specify an index file path manually, however, then you will have to always specify it because else it won't be found automatically. Unfortunately, this version is not yet on PyPI and it might take a while for me to do so. That's because yesterday, after noticing that my Travis time contingent ran out, I found out that Travis has changed their [payment](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works) [plans](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)  and I'll need to migrate to Github Actions. You can install the master branch version with:
```bash
pip install git+https://github.com/mxmlnkn/ratarmount.git
```

**Comment by mceachen** [comment] 2020-12-09 17:26
> ratarmount should detect whether the TAR file destination is writable

It's actually writable, but it's a remote file system, and SQLite doesn't support writing to remote file systems (I think due to the inability to mmap the .wal or .shm files as shared memory?). You could detect the "database is locked" error and write to ~/.ratarmount, but I think that's probably too clever by half.

Shame about Travis. It only took me about an hour, all-in, to switch several of my builds to Github Actions, so it may not be that bad.

**Comment by mxmlnkn** [comment] 2020-12-10 15:49
Could you paste the exception you get, so that I known what I have to catch to detect this error? I can't reproduce the problem on an sshfs mount.

Also, I'm thinking about adding a `--index-folder` option similar to the `--index-file` option.

**Comment by mceachen** [comment] 2020-12-10 17:30
```
~ ❯ ratarmount '/media/mrm/rusty2-home/mrm/example.tgz' ~/example
Creating offset dictionary for /media/mrm/rusty2-home/mrm/example.tgz ...
Creating new SQLite index database at /media/mrm/rusty2-home/mrm/example.tgz.index.sqlite
Traceback (most recent call last):
  File "/home/mrm/.local/bin/ratarmount", line 8, in <module>
    sys.exit(cli())
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 1728, in cli
    fuseOperationsObject = TarMount(
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 1122, in __init__
    self.mountSources = [ SQLiteIndexedTar( tarFile,
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 1122, in <listcomp>
    self.mountSources = [ SQLiteIndexedTar( tarFile,
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 313, in __init__
    self.createIndex( self.tarFileObject )
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 425, in createIndex
    self.sqlConnection.executescript( createTables )
sqlite3.OperationalError: database is locked
Exception ignored in: <function TarMount.__del__ at 0x7f7fd2ad3040>
Traceback (most recent call last):
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 1166, in __del__
    os.close( self.mountPointFd )
AttributeError: mountPointFd

~ took 5s ❯ ls -l '/media/mrm/rusty2-home/mrm/example.tgz.index.sqlite' 
-rwxr-xr-x 1 mrm root 0 Dec 10 09:17 /media/mrm/rusty2-home/mrm/example.tgz.index.sqlite

~ ❯ chmod ugo-rw /media/mrm/rusty2-home/mrm/example.tgz.index.sqlite

~ ❯ ratarmount '/media/mrm/rusty2-home/mrm/example.tgz' ~/example
[Warning] Could not load file '/media/mrm/rusty2-home/mrm/example.tgz.index.sqlite
[Info] Exception: SQLite index is empty
[Info] Some likely reasons for not being able to load the index file:
[Info]   - The index file has incorrect read permissions
[Info]   - The index file is incomplete because ratarmount was killed during index creation
[Info]   - The index file was detected to contain errors because of known bugs of older versions
[Info]   - The index file got corrupted because of:
[Info]     - The program exited while it was still writing the index because of:
[Info]       - the user sent SIGINT to force the program to quit
[Info]       - an internal error occured while writing the index
[Info]       - the disk filled up while writing the index
[Info]     - Rare lowlevel corruptions caused by hardware failure
[Info] This might force a time-costly index recreation, so if it happens often
       and mounting is slow, try to find out why loading fails repeatedly,
       e.g., by opening an issue on the public github page.
Creating offset dictionary for /media/mrm/rusty2-home/mrm/example.tgz ...
Creating new SQLite index database at /media/mrm/rusty2-home/mrm/example.tgz.index.sqlite
Traceback (most recent call last):
  File "/home/mrm/.local/bin/ratarmount", line 8, in <module>
    sys.exit(cli())
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 1728, in cli
    fuseOperationsObject = TarMount(
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 1122, in __init__
    self.mountSources = [ SQLiteIndexedTar( tarFile,
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 1122, in <listcomp>
    self.mountSources = [ SQLiteIndexedTar( tarFile,
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 313, in __init__
    self.createIndex( self.tarFileObject )
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 425, in createIndex
    self.sqlConnection.executescript( createTables )
sqlite3.OperationalError: database is locked
Exception ignored in: <function TarMount.__del__ at 0x7fc0a2b4b040>
Traceback (most recent call last):
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 1166, in __del__
    os.close( self.mountPointFd )
AttributeError: mountPointFd

~ took 5s ❯ rm '/media/mrm/rusty2-home/mrm/example.tgz.index.sqlite' 

~ ❯ ratarmount -d 3 '/media/mrm/rusty2-home/mrm/example.tgz' ~/example
Creating offset dictionary for /media/mrm/rusty2-home/mrm/example.tgz ...
Creating new SQLite index database at /media/mrm/rusty2-home/mrm/example.tgz.index.sqlite
Traceback (most recent call last):
  File "/home/mrm/.local/bin/ratarmount", line 8, in <module>
    sys.exit(cli())
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 1728, in cli
    fuseOperationsObject = TarMount(
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 1122, in __init__
    self.mountSources = [ SQLiteIndexedTar( tarFile,
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 1122, in <listcomp>
    self.mountSources = [ SQLiteIndexedTar( tarFile,
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 313, in __init__
    self.createIndex( self.tarFileObject )
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 425, in createIndex
    self.sqlConnection.executescript( createTables )
sqlite3.OperationalError: database is locked
Exception ignored in: <function TarMount.__del__ at 0x7f73d5937040>
Traceback (most recent call last):
  File "/home/mrm/.local/lib/python3.8/site-packages/ratarmount.py", line 1166, in __del__
    os.close( self.mountPointFd )
AttributeError: mountPointFd

~ took 5s ❯ mount | grep rusty2
//10.1.1.9/homes on /media/mrm/rusty2-home type cifs (rw,relatime,vers=3.1.1,sec=ntlmssp,cache=strict,username=mrm,uid=1000,forceuid,gid=0,noforcegid,addr=10.1.1.9,file_mode=0755,dir_mode=0755,soft,nounix,mapposix,rsize=4194304,wsize=4194304,bsize=1048576,echo_interval=60,actimeo=1)
```

I tried `chmod u-rw index.sqlite` to help exercise the "if we can't write to the sidecar, we'll write to ~/.ratarmount", but that code path didn't seem to activate. 

> I'm thinking about adding a --index-folder

That'd be wonderful.

While I'm asking for new features: have you considered making the -r option work for directories of tarballs? I can certainly run a for loop and mount them all individually, but a super-powered -r would be pretty sweet.

(In case you're interested in my usecase: fuse-mounting gigantic Google Takeout tarballs is much nicer than requiring 3x free disk space by extracting them).

**Comment by mxmlnkn** [comment] 2020-12-10 17:47
> While I'm asking for new features: have you considered making the -r option work for directories of tarballs? I can certainly run a for loop and mount them all individually, but a super-powered -r would be pretty sweet.

Ratarmount supports union mounting to some degree. Do you mean that? So, if you have something like:

```
 + foo.tar
 +- subfolder
     + bar.tar
 + test.tar
```

and if you wanted to mount all these tars under one mount point (and if there are no spaces in the names), you could do:

```bash
ratarmount $( find . -name '*.tar' ) mountpoint
```
> (In case you're interested in my usecase: fuse-mounting gigantic Google Takeout tarballs is much nicer than requiring 3x free disk space by extracting them).

It's always interesting to hear about applications for ratarmount!

**Comment by mceachen** [comment] 2020-12-10 18:11
> Do you mean that?

No, but that union stuff is fancy!

I've got a directory of ~100 .tgz files (say, in `/remote/dir`), and have all the files within the tgz exposed as if they were extracted in the same directory, so `ratarmount -r /remote/dir /mnt/dir` would expose the contents of, say, /remote/dir/89.tgz as /mnt/dir/89/...

But, again, a one line shell script will do this, just as well, I think (you'll just have 100 python processes, but that shouldn't be a problem). This is specifically to help people extricate themselves from Google Photos (and let [PhotoStructure](https://photostructure.com/faq/why-photostructure/) self-host and de-dupe their library: send me an email if you'd like a license).

Holler if you need any more debugging information from me, happy to help.

**Comment by mxmlnkn** [comment] 2020-12-10 18:50
> I've got a directory of ~100 .tgz files (say, in `/remote/dir`), and have all the files within the tgz exposed as if they were extracted in the same directory, so `ratarmount -r /remote/dir /mnt/dir` would expose the contents of, say, /remote/dir/89.tgz as /mnt/dir/89/...

Ah I see, union mounting would flatten the "outer" folder structure. Bind-mounting from one folder to another is actually already possible, so I think heeding the -r option in that case would definitely make sense. However, it might be a bit finicky to implement and, in your case, it might actually be better to mount all tars separately because ratarmount is not multithreaded. At least not consciously. FUSE should allow it, but I think the Python global interpreter lock would pose a problem.

You seem to have a similar setup as described in #38. Do you also see the performance issue that is reported there?

**Comment by mceachen** [comment] 2020-12-10 19:02
> because ratarmount is not multithreaded. At least not consciously

LOL

**Comment by mxmlnkn** [comment] 2020-12-10 21:28
> > because ratarmount is not multithreaded. At least not consciously
> 
> LOL

Oh :laughing: It seems I was too lazy to formulate my whole thought. I meant it like "I did not consciously add multithreading, but FUSE already does some implicit multithreading, so I'm not actually sure what really happens". Additionally there is the fusepy layer between FUSE and ratarmount.

I did implement a check, which actually tries to open an SQLite database and does not just check whether it can write a file.
I also added a `--index-folders` option, with which you can specify one ore more folders, which are checked in order. The first folder, which works for the index file, is then used. Allowing multiple folders makes it easy to map the current behavior to it as default arguments: an empty path specifying the TAR location plus a second path pointing to `~/.ratarmount`. However, allowing multiple arguments might lead to command line argument parsing problems if it precedes the positional arguments. I added an example showing how to circumvent this problem: `ratarmount --index-folders foo alternative -- my.tar mountpoint`.

I pushed these changes to the `develop` branch. You can test them out with:

```bash
pip install git+https://github.com/mxmlnkn/ratarmount.git@develop#egginfo=ratarmount
```

**Comment by mceachen** [comment] 2020-12-10 23:28
So, this works :100: 

` ratarmount --index-folders ~/.ratarmount -- /remote/file.tgz /mnt/file`

After looking at the docs, I'd expect this to work as well (without the `--`), but it doesn't seem to:

```sh
❯ ratarmount --index-folders ~/.ratarmount /remote/file.tgz /mnt/file
usage: ratarmount [-h] [-f] [-d DEBUG] [-c] [-r] [-gs GZIP_SEEK_POINT_SPACING] [-p PREFIX] [-e ENCODING] [-i] [--verify-mtime] [-s] [--index-file INDEX_FILE]
                  [--index-folders INDEX_FOLDERS [INDEX_FOLDERS ...]] [-o FUSE] [-v]
                  mount_source [mount_source ...] [mount_point]
ratarmount: error: the following arguments are required: mount_source
```

The vararg index-folders is powerful, but a bit ungainly to have to type repeatedly. Nothing `alias` can't fix, though:

```sh
alias tgzmount='ratarmount --index-folders ~/.ratarmount --'
```

Thanks (and if you want a PhotoStructure license, please email me: address is in the footer of the website).

**Comment by mxmlnkn** [comment] 2020-12-10 23:43
> After looking at the docs, I'd expect this to work as well (without the `--`), but it doesn't seem to:

At which doc? The problem is that it may get multiple arguments. If those multiple arguments are directly before the positional arguments, it becomes undecidable where the index folder arguments stop and the positional arguments begin. There already was a similar issue with the multiple possible mount sources and the optional mountpoint. However, I implemented some heuristics for that, e.g. the mount point can't be a file. It's not perfect either, though.

Alternatives would be to give the the multiple folders, as a JSON-like list, so `--index-folders "[ 'foo', 'alternative' ]"`. Of course, I would still allow the simple case of one folder `--index-folders foo`.

> The vararg index-folders is powerful, but a bit ungainly to have to type repeatedly. Nothing alias can't fix, though:

Did you test whether the [fallback](https://github.com/mxmlnkn/ratarmount/commit/0c21a5d1a703f741412e9a8117bdf9a20d8b0e28) works? It now tries to catch the OperationalError / DatabaseLocked error and should automatically choose `~/.ratarmount`,

**Comment by mceachen** [comment] 2020-12-10 23:49
> At which doc?

The docs from `--help` 👍

> The problem is that it may get multiple arguments

Right, and I totally see the value in supporting multiple directories. I just couldn't make it work with just one directory: I had to use `--`.

> Did you test whether the fallback works?

Yes, it didn't work for me. I'll post the error in a sec.

**Comment by mceachen** [comment] 2020-12-11 01:44
> You seem to have a similar setup as described in #38. Do you also see the performance issue that is reported there?

I've got 59 `ratarmount` processes running now, tracking > 1Tb of files. Running a `du -sh` took 12s (which is outstanding: it's over a slow NAS). Here's `top` during the du:

```
top - 17:42:08 up 6 days,  3:31,  1 user,  load average: 0.80, 1.35, 1.53
Tasks: 626 total,   3 running, 623 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.3 us,  1.3 sy,  0.0 ni, 94.2 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
MiB Mem :  64295.2 total,    469.2 free,  12386.1 used,  51440.0 buff/cache
MiB Swap:  16384.0 total,  15478.0 free,    906.0 used.  50442.1 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                             
1505177 mrm       20   0   13504   6788   1884 S  15.6   0.0   0:01.17 du                                                  
1409715 mrm       20   0 4891784 685712  61844 R  13.0   1.0  15:26.96 gnome-shell                                         
1494807 mrm       20   0   86540  62724   5112 S   7.3   0.1   0:01.19 ratarmount                                          
1494954 mrm       20   0   86356  61596   5196 S   7.3   0.1   0:01.10 ratarmount                                          
1496312 mrm       20   0   87916  63172   5260 S   7.0   0.1   0:01.05 ratarmount                                          
1495628 mrm       20   0   86640  61824   5180 S   6.6   0.1   0:01.10 ratarmount                                          
1496452 mrm       20   0   85936  61268   5264 S   6.6   0.1   0:01.07 ratarmount                                          
1496557 mrm       20   0   85052  60156   5104 R   6.3   0.1   0:01.24 ratarmount                                          
1495048 mrm       20   0   84816  60160   5264 S   5.6   0.1   0:00.92 ratarmount                                          
1495302 mrm       20   0   86696  61896   5160 S   5.6   0.1   0:00.96 ratarmount                                          
1495773 mrm       20   0   87444  62552   5184 S   5.6   0.1   0:00.94 ratarmount                                          
1495191 mrm       20   0   86148  61472   5248 S   5.0   0.1   0:00.81 ratarmount                                          
1495524 mrm       20   0   86936  62244   5248 S   4.7   0.1   0:00.77 ratarmount                                          
1495916 mrm       20   0   87388  62652   5236 S   4.3   0.1   0:00.65 ratarmount                                          
1496077 mrm       20   0   83524  59592   5156 S   3.7   0.1   0:00.63 ratarmount                                          
1495412 mrm       20   0   85560  60908   5280 S   3.3   0.1   0:00.62 ratarmount   
```

A++++, :star::star::star::star::star:, would ratarmount again.

**Comment by mxmlnkn** [comment] 2020-12-13 20:47
Fixed in master with 2c7c64ca15ae86d87f047ad6e308561714f2afd3. Even though I have ever-growing tests, I'm a bit hesistant to release yet. Will probably do a PyPI release next week though. The weird syntax with `--` is not necessary anymore. `--index-folders` now always takes only one string argument. However that string argument can be a folder, a comma separated list of folders, or a json list of folders.

**Closed by mxmlnkn** 2020-12-13 20:47 UTC

**Comment by mceachen** [comment] 2020-12-13 21:03
Excellent. I just updated to master with `pip3 install git+https://github.com/mxmlnkn/ratarmount.git --upgrade`.

* `ratarmount /remote/file.tgz ~/local` doesn't emit warnings anymore :+1: 
* the new `--index-folders` api is perfect. :+1: 
* tested that existing ~/.ratarmount indexes got loaded :+1: 
* tested that new indexes would be created in ~/.ratarmount on remote filesystems :+1: 
* testing multiple mounts `ratarmount /remote/file1.tgz /remote/file2.tgz ~/local` _did_ emit a warning about the index being empty, but it did work. It's a bit odd that the behaviour is different between mounting 1 vs 1 + N source files.

Thanks again!

**Comment by mxmlnkn** [comment] 2020-12-13 21:17
> - testing multiple mounts `ratarmount /remote/file1.tgz /remote/file2.tgz ~/local` _did_ emit a warning about the index being empty, but it did work. It's a bit odd that the behaviour is different between mounting 1 vs 1 + N source files.

Thank you for testing all this! I could definitely add some automated tests, which also tests the printed warnings. That takes a load off my heart because that's not the only change as xz and zst support also were added.

I can't reproduce the warning on the multiple mounts. In the first place, I still didn't find a filesystem yet with which to reproduce the SQLite problems. Generally, 1 vs 1+N source files shouldn't make a difference because I simply call the SQLiteIndexedTar class for each source under the hood. I strongly suspect that this error will also appear for one or both of these commands:

    ratarmount /remote/file1.tgz ~/local
    ratarmount /remote/file2.tgz ~/local

My test whether the location is suitable for an SQLite database does not clean up the created SQLite file properly when it can't write to it. That's why the second time you tried to mount it with ratarmount, it recognizes the empty database, removes it, and then searches for a suitable location again.

**Comment by mceachen** [comment] 2020-12-13 22:41
You should be able to test this by installing samba and mounting the default `home` or `homes` share (even against localhost).

> Should be fixed with c5cdb08.

Can confirm, LGTM. :rocket: :shipit:

**Comment by mxmlnkn** [comment] 2020-12-13 23:07
Thanks, I could confirm it with a local samba mount.

**Comment by mxmlnkn** [comment] 2020-12-19 11:32
> While I'm asking for new features: have you considered making the -r option work for directories of tarballs? I can certainly run a for loop and mount them all individually, but a super-powered -r would be pretty sweet.

Hi there again. I added this functionality including some tests on the develop branch. I'd still be glad if you could test it out and see whether that's what you wanted or whether I misunderstood you. Note that you can control the mount position a bit with `--strip-recursive-tar-extension`. So for example, you should be able to do:

    ratarmount --strip-recursive-tar-extension --recursive --index-folders "$( mktemp -d )" <my-folder-with-many-tars> <mount-point-with-all-those-tars-mounted>

**Comment by mceachen** [comment] 2020-12-19 17:15
`ratarmount --strip-recursive-tar-extension --recursive *.tgz ~/output` did exactly what I wanted: shipit!

**Comment by mceachen** [comment] 2020-12-19 17:20
Performance is equivalent, fwiw:

```sh
cd ~/output
du -sh .
562G	.
~/output🔒 took 1m51s ❯ 
```
(this is for 57 .tgz files all mounted to ~/output)

**Comment by mxmlnkn** [comment] 2020-12-20 13:38
Thank you for your time :)
