### ISSUE TITLE
Store/Index Recursive Archives

### ISSUE THREAD

**Issue by detain** [mxmlnkn/ratarmount#124] opened 2023-11-05 03:16 UTC
It seems that the recursive archive contents are not cached in the index.sqlite files.   Could this be added in a way that speeds up initial load time ?    Im recursively mounting over 10,000 archives with over 150,000 archives inside them and it would be nice to speed up this initial mount process.

**Comment by mxmlnkn** [comment] 2023-11-05 11:38
I kinda thought that it was possible to some extent. Guess I'll have to look into it again. I thought that the remaining difficulty was to index everything into the same index file because each recursive file would create its own index file, hopefully inside `~/.cache/ratarmount`  because the "folder", in which the recursive file resides in, is not writable.

Just to get a better feel. How large arge the contained archives and what compression is used for the outer and inner archive? Is it a public dataset that I can use for benchmark purposes?

**Comment by mxmlnkn** [comment] 2024-02-23 21:23
I'm still missing the exact archive formats/compressions, but I'll close it as a likely duplicate of #79.

**Closed by mxmlnkn** 2024-02-23 21:23 UTC
Labels: enhancement
